apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-app
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  selector:
    matchLabels:
      app: account-app
  replicas: 1
  template:
    metadata:
      labels:
        app: account-app
    spec:
      containers:
        # ACCOUNT SERVICE DEPLOYMENT
        - name: account-service
          image: gcr.io/rb08-streamy/account-service:staging
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
            - name: ACCOUNT_SERVICE_NAME
              value: account-service
            - name: DB_NAME
              value: account
            - name: DB_HOST
              value: 10.57.96.3
            - name: DB_PASSWORD
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: RABBIT_MQ_URI
              value: amqp://rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: RABBIT_MQ_ACCOUNT_QUEUE
              value: account
