apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  selector:
    matchLabels:
      app: auth-app
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      volumes:
        - name: gke-cloud-account-service-secret-volume
          secret:
            secretName: gke-cloud-account-service-secrets
      containers:
        # AUTH SERVICE DEPLOYMENT
        - name: auth-service
          image: gcr.io/RB08-streamy/auth-service:staging
          imagePullPolicy: Always
          env:
            - name: PORT
              value: 80
            - name: AUTH_SERVICE_NAME
              value: auth-service
            - name: DB_NAME
              value: auth
            - name: DB_HOST
              value: 10.57.96.3
            - name: DB_PASSWORD
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PORT
              value: 5432
            - name: JWT_SECRET
              value: secret
            - name: JWT_EXPIRATION
              value: 3600
            - name: RABBIT_MQ_URI
              value: amqp://rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: RABBIT_MQ_ACCOUNT_QUEUE
              value: account
