apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        # GATEWAY DEPLOYMENT
        - name: gateway
          image: gcr.io/RB08-streamy/gateway-service:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: GATEWAY_PORT
              value: 80
            - name: AUTH_SERVICE_HOST
              value: auth-service
            - name: MOVIE_SERVICE_HOST
              value: movie-service
            - name: ACCOUNT_SERVICE_HOST
              value: account-service
            - name: WEB_PORT
              value: 3000
            - name: WEB_HOST
              value: web-service
