apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies-app
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service-deployment
spec:
  selector:
    matchLabels:
      app: movies-app
  replicas: 1
  template:
    metadata:
      labels:
        app: movies-app
    spec:
      containers:
        # MOVIES SERVICE DEPLOYMENT
        - name: movies-service
          image: gcr.io/rb08-streamy/movies-service:staging
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
            - name: MOVIES_SERVICE_NAME
              value: movies-service
            - name: DB_NAME
              value: movies
            - name: DB_HOST
              value: 10.57.96.3
            - name: DB_PASSWORD
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: RABBIT_MQ_URI
              value: amqp://rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
