name: Movies Service

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/movies/**'
      - '.github/workflows/build-staging-movies-service.yml'

concurrency: staging-movies-service

env:
  SERVICE_NAME: movies
  DEPLOYMENT_NAME: movies-service-deployment
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: notflix
  GKE_ZONE: europe-west4-a

jobs:
  build:
    name: Build staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build and Push
        uses: ./.github/workflows/composite/build
        with:
          service_name: ${{ env.SERVICE_NAME }}
          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
          registry_token: ${{ secrets.GOOGLE_CONTAINER_REGISTRY_TOKEN }}

#  deploy:
#    needs: [build]
#    if: success()
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v1
#
#      - name: Deploy to GKE
#        uses: ./.github/workflows/composite/deploy
#        with:
#          service_account_key: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
#          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
#          cluster_name: ${{ env.GKE_CLUSTER }}
#          location: ${{ env.GKE_ZONE }}
#          credentials: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
#          deploy_name: ${{ env.DEPLOYMENT_NAME }}
